# Generated by Django 5.2.1 on 2025-09-19 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("friend_request_received", "Friend Request Received"),
                            ("friend_request_accepted", "Friend Request Accepted"),
                            ("friend_request_declined", "Friend Request Declined"),
                            ("user_kick", "User Kick"),
                            ("user_block", "User Block"),
                            ("user_unblock", "User Unblock"),
                            ("group_request_received", "Group Request Received"),
                            ("group_request_accepted", "Group Request Accepted"),
                            ("group_request_declined", "Group Request Declined"),
                            ("group_kick", "Group Kick"),
                            ("group_block", "Group Block"),
                            ("group_unblock", "Group Unblock"),
                        ],
                        max_length=30,
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notification_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_notifications_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notification_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_notifications_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
