# Generated by Django 5.2.1 on 2025-06-12 14:41

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "training_plans",
            "0002_trainingplan_is_public_alter_trainingplan_is_active_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainingplanusage",
            name="get_at",
        ),
        migrations.AddField(
            model_name="trainingplanusage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="exerciseset",
            name="repetitions",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="exerciseset",
            name="set_index",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(50),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="trainingplan",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="trainingplanrating",
            name="comment",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="trainingplanrating",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="trainingplanrating",
            name="rating",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="trainingplanrating",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="workout",
            name="description",
            field=models.TextField(),
        ),
    ]
