# Generated by Django 5.2.1 on 2025-07-03 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0002_alter_exercise_description_and_more"),
        ("training_plans", "0003_remove_trainingplanusage_get_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exerciseset",
            old_name="set_index",
            new_name="set_number",
        ),
        migrations.RemoveField(
            model_name="exerciseset",
            name="exercise",
        ),
        migrations.RemoveField(
            model_name="exerciseset",
            name="workout",
        ),
        migrations.CreateModel(
            name="WorkoutExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workouts",
                        to="exercises.exercise",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="training_plans.workout",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="exerciseset",
            name="workout_exercise",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercise_sets",
                to="training_plans.workoutexercise",
            ),
            preserve_default=False,
        ),
    ]
