# Generated by Django 5.2.1 on 2025-08-31 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_profile_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="bodyweight",
            new_name="body_weight",
        ),
    ]
