# Generated by Django 5.2.1 on 2025-06-12 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("friendships", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="friendship",
            name="blocked_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocked_friendships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="friendrequest",
            name="message",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="friendrequest",
            name="responded_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="friendrequest",
            name="sent_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="friendship",
            name="blocked_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="friendship",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="friendship",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_friendships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
