# Generated by Django 5.2.1 on 2025-09-04 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "friendships",
            "0002_friendship_blocked_by_alter_friendrequest_message_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="friendship",
            name="kicked_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="friendship",
            name="kicked_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kicked_friendships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="friendship",
            name="blocked_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="friendship",
            name="status",
            field=models.CharField(
                choices=[
                    ("accepted", "Active"),
                    ("kicked", "Kicked"),
                    ("blocked", "Blocked"),
                ],
                max_length=30,
            ),
        ),
    ]
