# Generated by Django 5.2.1 on 2025-05-30 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2000)),
                ('image', models.ImageField(default='group_pics/default.jpg', upload_to='group_pics')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_hosted', to=settings.AUTH_USER_MODEL)),
                ('join_requests', models.ManyToManyField(related_name='groups_join_requests', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='groups_belonging', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
