# Generated by Django 5.2.1 on 2025-06-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="groupaddrequest",
            name="message",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="groupaddrequest",
            name="responded_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="groupaddrequest",
            name="sent_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="groupmembership",
            name="blocked_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="groupmembership",
            name="kicked_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="groupmembership",
            name="started_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
