# Generated by Django 5.2.1 on 2025-08-25 17:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_alter_group_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="groupmembership",
            name="blocked_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="groupmembership",
            name="kicked_at",
            field=models.DateTimeField(null=True),
        ),
    ]
