# Generated by Django 5.2.1 on 2025-09-03 21:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_group_created_at_alter_groupmembership_blocked_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="groupaddrequest",
            unique_together={("user", "group", "status")},
        ),
    ]
