# Generated by Django 5.2.1 on 2025-09-03 21:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0004_alter_groupaddrequest_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="groupaddrequest",
            unique_together={("user", "group", "status", "sent_at", "responded_at")},
        ),
    ]
