# Generated by Django 5.2.1 on 2025-06-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_performance', '0002_alter_exercisesetperformance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisesetperformance',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
