# Generated by Django 5.2.1 on 2025-05-31 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_performance', '0002_alter_exercisesetperformance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisesetperformance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 31, 9, 58, 53, 90627)),
        ),
    ]
