# Generated by Django 5.2.1 on 2025-06-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout_performance", "0003_alter_exercisesetperformance_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercisesetperformance",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="exercisesetperformance",
            name="repetitions_done",
            field=models.PositiveIntegerField(),
        ),
    ]
